id: P004303
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC241
  title: 'འཚོལ་ཞིབ་དང་མཐའ་དཔྱོད། '
  author: ''
  volumes:
    b0cb651453844c1aaa3c2469d4a9e03a:
      image_group_id: I2PD17971
      title: ''
      volume_number: 1
      total_pages: 680
      base_file: v001.txt
